linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated

linters:
  enable-all: true
  disable:
    - testpackage
    - varnamelen
    # deprecated :(
    - interfacer
    - maligned
    - scopelint
    - golint
  fast: false

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    - path: ._test\.go
      linters:
        - exhaustivestruct
